name: frontend_lint
on: [pull_request]
jobs:
  lint:
    name: lint
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -D
      - run: npm run format
