name: frontend
on: [pull_request]
jobs:
  lint:
    name: lint
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -D
      - run: | 
          npm run format
          npm run lint
      - name: elist & prettier
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: eslint & prettier
